import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import TestBut from "./components/testbut";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-blue-500 flex justify-center gap-4 fixed top-0 right-0 left-0 z-10">
          <Link href="/">Home</Link>
          <Link href="/home">Login</Link>
          {/* TODO: Remove later */}
          <TestBut></TestBut> 
        </nav>
        {children}
      </body>
    </html>
  );
}
